### ISSUE TITLE
TCreator attempts to read from an non-existent file while creating a sword

### ISSUE THREAD

**Issue by Soniczac7** [Henrymistert123/TCreator#5]
Exception Type: System.IO.DirectoryNotFoundException
Exception Message: Could not find a part of the path 'D:\TCreator\TCreator\bin\Debug\net6.0-windows\Examples\Items\Sword\ExampleSword.txt'.
Exception StackTrace:
```
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs:line 57
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in /_/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Windows.cs:line 35
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/OSFileStreamStrategy.cs:line 50
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.Windows.cs:line 36
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.cs:line 34
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamReader.cs:line 233
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding) in /_/src/libraries/System.Private.CoreLib/src/System/IO/File.cs:line 416
   at System.IO.File.ReadAllLines(String path) in /_/src/libraries/System.Private.CoreLib/src/System/IO/File.cs:line 392
   at TCreator.Sword.button1_Click(Object sender, EventArgs e) in D:\TCreator\TCreator\Sword.cs:line 24
   at System.Windows.Forms.Control.OnClick(EventArgs e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 7746
   at System.Windows.Forms.Button.OnClick(EventArgs e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Button.cs:line 258
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Button.cs:line 291
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 12439
   at System.Windows.Forms.Control.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13229
   at System.Windows.Forms.ButtonBase.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs:line 1341
   at System.Windows.Forms.Button.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Button.cs:line 396
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 68
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 122
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 370
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs:line 346
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 1117
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 981
   at System.Windows.Forms.Application.Run(Form mainForm) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1188
   at TCreator.Program.Main() in D:\TCreator\TCreator\Program.cs:line 14```

**Comment by Henrymistert123** [comment]
You have to put the examples folder in the same folder of TCreator when you build it
